#! /bin/sh

PANEL_WM=panel_bottom
PANEL_FIFO=/tmp/panel_bottom_fifo

if xdo id -a "$PANEL_WM" > /dev/null ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

source $(dirname $0)/config_bar

music() {
    local icon=$(pIcon ${MAGENTA} ${CSOUND})
    local stat="$(mpc status | grep \# | awk '{print $1}')"
    local artist=$(mpc -f %artist% current)
    local musicname=$(mpc -f %title% current)
    local cmd=""

    if [ "${stat}" ] && [ "${stat}" = "[playing]" ] ; then
        _artist=$(pText ${MAGENTA} "${artist:0:10}")
        _music=$(pText ${BLUE2} "${musicname:0:25}")
        cmd=" playing $_artist * $_music"
    elif [ "${stat}" ] && [ "${stat}" = "[paused]" ] ; then
        _artist=$(pText ${MAGENTA} "${artist:0:10}")
        _music=$(pText ${BLUE2} "${musicname:0:25}")
        cmd=" paused $_artist * $_music"
    else
        cmd=" no sound"
    fi

    echo "${icon}$(pText ${WHITE} "${cmd}")"
}

volume() {
    local icon=$(pIcon ${MAGENTA} ${CVOLUME})
    local vol="$(mpc volume | awk '{print $2}')"
    [[ -z ${vol} ]] && vol='100%'
    local clr=$(pText ${FG} "${vol}")
    echo "${icon} ${clr}"
}

net() {
    local _GETIWL=$(/sbin/iwgetid -r)
    local _GETETH=$(ip a | grep "state UP" | awk '{ORS=""}{print $2}' | cut -d ':' -f 1)
    local _status=${_GETIWL:-$_GETETH}
    local _status2="${_status:-Down}"
    local icon="$(pIcon ${MAGENTA} ${CNET})"
    local cmd=$(pText ${WHITE} " ${_status2} ")

    echo "${icon}${cmd}"
} 

wifi_str() {
    local _icon=$(pIcon ${MAGENTA} ${WIFI_STR})
    local _cmd=$(/sbin/iwconfig 2>/dev/null | grep "Link Quality" | cut -d "=" -f 2 | awk '{print $1}')
    echo "${_icon} ${_cmd}"
}

cpu() {
    local icon=$(pIcon ${MAGENTA} ${CCPU})
    local cmd=" $(cat /proc/loadavg | awk '{print $1}')"
    local cmd+=" $(cat /proc/loadavg | awk '{print $4}')"
    local cmd+=" $(cat /proc/cpuinfo| grep MHz | awk '{ORS=" "}{print $4}' | sed -e 's/.000//g' | cut -f 1)"

    local clr=$(pText ${WHITE} "${cmd}")
    echo "${icon}${clr}"
}

ram() {
    local icon=$(pIcon ${MAGENTA} ${CRAM})
    local cmd=$(free -m | grep Mem | awk '{print $3}')
    cmd+=" Mb"
    local clr=$(pText ${WHITE} "${cmd}")
    echo "${icon} ${clr}"
}

{
    while :; do
        echo "W $(music) $(volume)"
        echo "A$(cpu) $(ram)"
        echo "R$(wifi_str) $(net)" 
        sleep 1
    done > "$PANEL_FIFO" &
}

{
    while read -r line ; do
        cmd=( $line )
        case "${cmd[0]}" in
            W*)
                sysL="${line#?}"
                ;;
            A*)
                wm="${line#?}"
                ;;
            R*)
                sysR="${line#?}"
                ;;
            reload)
                exit
                ;;
            quit_panel)
                exit
                ;;
        esac
        printf "%s\n" "%{l}${sysL}%{c}${wm}%{r}${sysR}"
    done
} < "$PANEL_FIFO" | lemonbar \
    -n ${PANEL_WM} -g x${HEIGHT} -u 2 -B ${BG} -F ${FG} -f "${FONT}" -f "${FONT_ICON}" -b | sh &

wid=$(xdo id -m -a "$PANEL_WM")
xdo above -t "$(xdo id -N I3Bottom -n root | sort | head -n 1)" "$wid"

wait
