# To display terminal icon: (nerd-font, icomoon)
# echo "\u<code>", e.g: echo "\uf09c2"
[global]
    font = IosevkaTerm Nerd Font 14
    frame_width = 4
    frame_color = "#2c303a" # inverse-on-surface
    format = "<span rise='-5000' font_desc='Material Symbols Outlined Regular 20'>%I</span><span foreground='#2c303a'> %s</span><span font_desc='Iosevka Nerd Font Regular 14' foreground='#2c303a'> &gt; %b</span>"

[urgency_low]
    background = "#dfe2ef" # inverse-surface
    foreground = "#005bbd" # inverse-primary
    timeout = 5
    # Icon for notifications with low urgency
    default_icon = dialog-information

[urgency_normal]
    background = "#dfe2ef" # inverse-surface
    foreground = "#005bbd" # inverse-surface
    timeout = 5
    override_pause_level = 30
    # Icon for notifications with normal urgency
    default_icon = dialog-information

[urgency_critical]
    background = "#ffb4ab"
    foreground = "#690005"
    frame_color = "#ffb4ab"
    timeout = 0
    override_pause_level = 60
    # Icon for notifications with critical urgency
    default_icon = dialog-warning

[kew_display]
    appname = kew
    urgency = low
    format = "<span rise='-5000' font_desc='Material Symbols Outlined Regular 20'>music_note_2</span><span foreground='#2c303a'> Kew</span> &gt; <span font_desc='Iosevka Nerd Font Regular 14' foreground='#2c303a'>%b</span>"
    history_ignore = yes
