background #0f131c
foreground #dfe2ef
cursor #dfe2ef

color0 #1c1f2e
color1 #de8387
color2 #74acca
color3 #95acdf
color4 #8584de
color5 #beb4e7
color6 #a385dc
color7 #d3d5de

color8 #7178a0
color9 #ffb4ab
color10 #9ecae2
color11 #bccceb
color12 #aeadfc
color13 #d1cbf1
color14 #bda4eb
color15 #f1f1f4

# The foreground for selections
selection_foreground #002f67
# The background for selections
selection_background #004491

# Emacs background :backgroud
color17    #0f131c

# Emacs modeline
color23 #7178a0
# Color 66 is set to the value of color0 even when bold.
# color66 #7178a0

# The color for the border of the active window
active_border_color #95acdf

# The color for the border of inactive windows
inactive_border_color #7178a0

# bright blue 12
url_color #aeadfc

# on-primary
active_tab_foreground #002f67
# primary
active_tab_background #acc7ff
# foreground
inactive_tab_foreground #2a2e4d
# black
inactive_tab_background #c0c4eb
tab_bar_background none

# Marks
mark1_foreground black
mark1_background #5599E2
mark2_foreground black
mark2_background #DDDBCF
mark3_foreground black
mark3_background #956dca
