#!/bin/sh

set -e

daemon=${1:?}
state="%{F#b47f6f}off%{F-}"
cmd="$(systemctl status $daemon | grep -i run 2>/dev/null || echo '')"

[[ "$cmd" ]] && state="%{F#fae0cf}on%{F-}"

echo "%{F#af8787}${daemon}%{F-} ${state}"
exit 0
